helpers.js
helpers.test.js
package-lock.json
parsers.js
validators.js
validators.test.js

https://kaholo.atlassian.net/browse/KP-712

[KP-712] Add secret key files handling

---

helpers.js
helpers.test.js

[**KP-744 in Jira**](https://kaholo.atlassian.net/browse/KP-744)

KP-744 [kaholo-plugin-library] Create function for extracting and parsing file paths for CLI commands.

---

package.json
parsers.js

https://kaholo.atlassian.net/browse/KP-767

[KP-767] Trim every value parsed as string

---

docker.js
docker.test.js
helpers.js
helpers.test.js
kaholo-plugin-library.js
package-lock.json
package.json

[**KP-776 in Jira**](https://kaholo.atlassian.net/browse/KP-776)

KP-776 [kaholo-plugin-library] Create Docker CLI helper functions

---

docker.js
docker.test.js
package.json

https://kaholo.atlassian.net/browse/KP-810

[KP-810] Simplify Docker functions

---

parsers.js

[**KP-825 in Jira**](https://kaholo.atlassian.net/browse/KP-825)

KP-825 [Text Editor] Newlines are not handled correctly

---

parsers.js

[**KP-850 in Jira**](https://kaholo.atlassian.net/browse/KP-850)

Add json parser

---

helpers.js

https://kaholo.atlassian.net/browse/KP-885

[KP-885] mktemp no longer works

---

core.js
helpers.js
package-lock.json
parsers.js

[**KP-1086 in Jira**](https://kaholo.atlassian.net/browse/KP-1086)

[KP-1086] Add new "filePath" parser and "analyzePath" helper function

---

autocomplete.js
config-loader.js
core.js
helpers.js

[**KP-1129 in Jira**](https://kaholo.atlassian.net/browse/KP-1129)

[KP-1129]([kaholo-plugin-library] Fix parsing parameters passed to the autocomplete functions)

---

parsers.js

[**KP-1168 in Jira**](https://kaholo.atlassian.net/browse/KP-1168)

KP-1168 ([kaholo-plugin-library] Add AWS Tags parser)

---

autocomplete.js
helpers.js

I discovered some bugs in `kaholo-plugin-library` when testing `aws-plugin-library`, this PR fixes them.

Fix duplication bug and undefined method definition bug

---

autocomplete.js
helpers.js
package.json

Fixed:
* Parsing of the autocomplete function parameters

KP-1172 (Release v2.2.1)

---

autocomplete.js
helpers.js
package.json

Reverts Kaholo/kaholo-plugin-library#43

Revert "KP-1172 (Release v2.2.1)"

---

core.js
secrets-redaction.js

[**KP-1153 in Jira**](https://kaholo.atlassian.net/browse/KP-1153)

KP-1153 ([MySQL CLI] Password not redacted when there's an error)

---

core.js
helpers.js

[**KP-1191 in Jira**](https://kaholo.atlassian.net/browse/KP-1191)

KP-1191 ([JSON] When boolean is configured false, config.json default overrides it as true)

---

package.json

Fixed:
* [**KP-1204**](https://kaholo.atlassian.net/browse/KP-1204) Numeric results being treated as empty results
* [**KP-1205**](https://kaholo.atlassian.net/browse/KP-1205) Autocomplete functions receiving bad parameters

Release v2.3.1

---

helpers.test.js

[**KP-1210 in Jira**](https://kaholo.atlassian.net/browse/KP-1210)

KP-1210 (Simple Unit Tests for Kaholo Plugin Library)

---

autocomplete.js
core.js

[**KP-1242 in Jira**](https://kaholo.atlassian.net/browse/KP-1242)

KP-1242 ([kaholo-plugin-library] Autocomplete breaks if required params not provided)

---

autocomplete.js
core.js
helpers.js
helpers.test.js
package.json

Fixed:
* **[KP-1242](https://kaholo.atlassian.net/browse/KP-1242)** Required params in autocomplete function bug
* **[KP-1204](https://kaholo.atlassian.net/browse/KP-1204)** Empty result condition
[KP-1242]: https://kaholo.atlassian.net/browse/KP-1242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KP-1204]: https://kaholo.atlassian.net/browse/KP-1204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[KP-1246] Release v2.3.2

---

parsers.js

[**KP-1257 in Jira**](https://kaholo.atlassian.net/browse/KP-1257)

KP-1257 ([AWS EC2] method Create Route Table parameter Tags - doesn't allow tags without values)
